name: release game

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "release tag"
        required: true
      name:
        description: "release name"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: determine release tag
        id: release_tag
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "RELEASE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            echo "RELEASE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi

      - name: determine release name
        run: |
          if [ -n "${{ github.event.inputs.name }}" ]; then
            echo "RELEASE_NAME=${{ github.event.inputs.name }}" >> $GITHUB_ENV
          else
            echo "RELEASE_NAME=${{ env.RELEASE_TAG }}" >> $GITHUB_ENV
          fi

      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y zip wget unzip

      - name: get release notes
        id: commits
        run: |
          if [ -n "${GITHUB_REF_NAME}" ]; then
            RELEASE_BODY=$(git log --pretty=format:'- %s (%h)' ${GITHUB_REF}^..${GITHUB_REF} || echo "no commits found")
          else
            RELEASE_BODY=$(git log -n 10 --pretty=format:'- %s (%h)')
          fi
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: package .love
        run: |
          zip -r DELTARUNE-vessel.love . -x "*.git*" ".github/*" "kristal/*"

      - name: download love for windows
        run: |
          curl -L -o love-11.4-win32.zip https://github.com/love2d/love/releases/download/11.4/love-11.4-win32.zip
          unzip love-11.4-win32.zip -d love-win

      - name: build exe
        run: |
          cat love-win/love-11.4-win32/love.exe DELTARUNE-vessel.love > DELTARUNE-vessel.exe

      - name: create pre-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          body: |
            changes:
            ${{ env.RELEASE_BODY }}
          draft: false
          prerelease: true
          files: |
            DELTARUNE-vessel.love
            DELTARUNE-vessel.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
